{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "553a2e19",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "from PyQt5.QtWidgets import QWidget, QPushButton, QApplication\n",
    "from PyQt5.QtCore import QCoreApplication\n",
    "from PyQt5.QtWidgets import QFileDialog\n",
    "import wave, contextlib, math, time\n",
    "import speech_recognition as sr\n",
    "from moviepy.editor import AudioFileClip\n",
    "from PyQt5 import QtCore, QtGui, QtWidgets\n",
    "from PyQt5.QtWidgets import QFileDialog, QMessageBox\n",
    "from PyQt5.QtCore import QThread, pyqtSignal\n",
    "\n",
    "import os\n",
    "from pydub import AudioSegment\n",
    "from pydub.silence import split_on_silence #это для того чтобы разделять код на куски\n",
    "\n",
    "\n",
    "class Ui_MainWindow(object):\n",
    "    \"\"\"Main window GUI.\"\"\"\n",
    "    def __init__(self):\n",
    "        \"\"\"Initialisation function.\"\"\"\n",
    "        self.mp4_file_name = \"\"\n",
    "        self.output_file = \"\"\n",
    "        self.audio_file = \"speech.wav\"\n",
    "        \n",
    "    def setupUi(self, MainWindow):\n",
    "        \"\"\"Define visual components and positions.\"\"\"\n",
    "        # Main window\n",
    "        MainWindow.setObjectName(\"MainWindow\")\n",
    "        MainWindow.resize(750, 900)\n",
    "        self.centralwidget = QtWidgets.QWidget(MainWindow)\n",
    "        self.centralwidget.setObjectName(\"centralwidget\")\n",
    "        self.label = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.label.setGeometry(QtCore.QRect(50, 20, 260, 41))\n",
    "        # Selected video file label\n",
    "        font = QtGui.QFont()\n",
    "        font.setPointSize(14)\n",
    "        self.label.setFont(font)\n",
    "        self.label.setObjectName(\"label\")\n",
    "        self.selected_video_label = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.selected_video_label.setGeometry(QtCore.QRect(330, 20, 371, 41))\n",
    "        font = QtGui.QFont()\n",
    "        font.setPointSize(8)\n",
    "        self.selected_video_label.setFont(font)\n",
    "        self.selected_video_label.setFrameShape(QtWidgets.QFrame.Box)\n",
    "        self.selected_video_label.setText(\"\")\n",
    "        self.selected_video_label.setObjectName(\"selected_video_label\")\n",
    "        self.label_3 = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.label_3.setGeometry(QtCore.QRect(50, 90, 260, 41))\n",
    "        # Transcribed text box\n",
    "        font = QtGui.QFont()\n",
    "        font.setPointSize(14)\n",
    "        self.label_3.setFont(font)\n",
    "        self.label_3.setObjectName(\"label_3\")\n",
    "        self.transcribed_text = QtWidgets.QTextBrowser(self.centralwidget)\n",
    "        self.transcribed_text.setGeometry(QtCore.QRect(330, 320, 381, 431))\n",
    "        self.transcribed_text.setObjectName(\"transcribed_text\")\n",
    "        self.label_5 = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.label_5.setGeometry(QtCore.QRect(330, 280, 260, 41))\n",
    "        font = QtGui.QFont()\n",
    "        font.setPointSize(14)\n",
    "        self.label_5.setFont(font)\n",
    "        self.label_5.setObjectName(\"label_5\")\n",
    "        self.transcribe_button = QtWidgets.QPushButton(self.centralwidget)\n",
    "        self.transcribe_button.setEnabled(False)\n",
    "        self.transcribe_button.setGeometry(QtCore.QRect(330, 150, 221, 81))\n",
    "        # Transcribe button\n",
    "        font = QtGui.QFont()\n",
    "        font.setPointSize(14)\n",
    "        self.transcribe_button.setFont(font)\n",
    "        self.transcribe_button.setObjectName(\"transcribe_button\")\n",
    "        self.transcribe_button.clicked.connect(self.process_and_transcribe_audio)\n",
    "        # progress bar\n",
    "        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)\n",
    "        self.progress_bar.setGeometry(QtCore.QRect(330, 250, 381, 23))\n",
    "        self.progress_bar.setProperty(\"value\", 0)\n",
    "        self.progress_bar.setObjectName(\"progress_bar\")\n",
    "        self.message_label = QtWidgets.QLabel(self.centralwidget)\n",
    "        self.message_label.setGeometry(QtCore.QRect(50, 770, 650, 21))\n",
    "        # Message label (for errors and warnings)\n",
    "        font = QtGui.QFont()\n",
    "        font.setPointSize(8)\n",
    "        self.message_label.setFont(font)\n",
    "        self.message_label.setFrameShape(QtWidgets.QFrame.Box)\n",
    "        self.message_label.setText(\"\")\n",
    "        self.message_label.setObjectName(\"message_label\")\n",
    "        self.output_file_name = QtWidgets.QPlainTextEdit(self.centralwidget)\n",
    "        self.output_file_name.setGeometry(QtCore.QRect(330, 90, 371, 41))\n",
    "        # Output file name\n",
    "        font = QtGui.QFont()\n",
    "        font.setPointSize(14)\n",
    "        self.output_file_name.setFont(font)\n",
    "        self.output_file_name.setObjectName(\"output_file_name\")\n",
    "        # Menubar options\n",
    "        MainWindow.setCentralWidget(self.centralwidget)\n",
    "        self.menubar = QtWidgets.QMenuBar(MainWindow)\n",
    "        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 21))\n",
    "        self.menubar.setObjectName(\"menubar\")\n",
    "        self.menuFile = QtWidgets.QMenu(self.menubar)\n",
    "        self.menuFile.setObjectName(\"menuFile\")\n",
    "        self.menuAbout = QtWidgets.QMenu(self.menubar)\n",
    "        self.menuAbout.setObjectName(\"menuAbout\")\n",
    "        self.menuSet = QtWidgets.QMenu(self.menubar)\n",
    "        self.menuSet.setObjectName(\"menuSet\")\n",
    "        MainWindow.setMenuBar(self.menubar)\n",
    "        self.statusbar = QtWidgets.QStatusBar(MainWindow)\n",
    "        self.statusbar.setObjectName(\"statusbar\")\n",
    "        MainWindow.setStatusBar(self.statusbar)\n",
    "        self.actionOpen_mp4_video_recording = QtWidgets.QAction(MainWindow)\n",
    "        self.actionOpen_mp4_video_recording.setObjectName(\"actionOpen_mp4_video_recording\")\n",
    "        self.actionOpen_mp4_video_recording.triggered.connect(self.open_audio_file)\n",
    "        self.actionAbout_vid2text = QtWidgets.QAction(MainWindow)\n",
    "        self.actionAbout_vid2text.setObjectName(\"actionAbout_vid2text\")\n",
    "        self.actionAbout_vid2text.triggered.connect(self.show_about)\n",
    "        self.actionTriggers = QtWidgets.QAction(MainWindow)\n",
    "        self.actionTriggers.setObjectName(\"actionTriggers\")\n",
    "        self.actionTriggers.triggered.connect(self.show_about)\n",
    "        self.actionNew = QtWidgets.QAction(MainWindow)\n",
    "        self.actionNew.setObjectName(\"actionNew\")\n",
    "        self.actionNew.triggered.connect(self.new_project)\n",
    "        self.menuFile.addAction(self.actionOpen_mp4_video_recording)\n",
    "        self.menuFile.addAction(self.actionNew)\n",
    "        self.menuAbout.addAction(self.actionAbout_vid2text)\n",
    "        self.menuSet.addAction(self.actionTriggers)\n",
    "        self.menubar.addAction(self.menuFile.menuAction())\n",
    "        self.menubar.addAction(self.menuAbout.menuAction())\n",
    "        self.retranslateUi(MainWindow)\n",
    "        QtCore.QMetaObject.connectSlotsByName(MainWindow)\n",
    "        \n",
    "    def retranslateUi(self, MainWindow):\n",
    "        \"\"\"Translate UI method.\"\"\"\n",
    "        _translate = QtCore.QCoreApplication.translate\n",
    "        MainWindow.setWindowTitle(_translate(\"MainWindow\", \"Переводчик текста\"))\n",
    "        self.label.setText(_translate(\"MainWindow\", \"Выбранный видеофайл:\"))\n",
    "        self.label_3.setText(_translate(\"MainWindow\", \"Выходной файл:\"))\n",
    "        self.label_5.setText(_translate(\"MainWindow\", \"Текст:\"))\n",
    "        self.transcribe_button.setText(_translate(\"MainWindow\", \"Создать протокол\"))\n",
    "        self.output_file_name.setPlaceholderText(_translate(\"MainWindow\", \"textinterview.txt\"))\n",
    "        self.menuFile.setTitle(_translate(\"MainWindow\", \"Файл\"))\n",
    "        self.menuAbout.setTitle(_translate(\"MainWindow\", \"О программе\"))\n",
    "        self.menuSet.setTitle(_translate(\"MainWindow\", \"Настройки\"))\n",
    "        self.actionOpen_mp4_video_recording.setText(_translate(\"MainWindow\", \"Загрузить\"))\n",
    "        self.actionAbout_vid2text.setText(_translate(\"MainWindow\", \"О транскрибации\"))\n",
    "        self.actionNew.setText(_translate(\"MainWindow\", \"Новый фай:\"))\n",
    "        self.actionTriggers.setText(_translate(\"MainWindow\", \"Редактировать триггеры\"))\n",
    "        \n",
    "    def open_audio_file(self):\n",
    "        \"\"\"Open the audio (*.mp4) file.\"\"\"\n",
    "        file_name = QFileDialog.getOpenFileName()\n",
    "        if file_name[0][-3:] == \"mp4\":\n",
    "            self.transcribe_button.setEnabled(True)\n",
    "            self.mp4_file_name = file_name[0]\n",
    "            self.message_label.setText(\"\")\n",
    "            self.selected_video_label.setText(file_name[0])\n",
    "        else:\n",
    "            self.message_label.setText(\"Пожалуйста, выберите *.mp4 файл.\")\n",
    "            \n",
    "    def convert_mp4_to_wav(self):\n",
    "        \"\"\"Convert the mp4 video file into an audio file.\"\"\"\n",
    "        self.message_label.setText(\"Конвертирование mp4 в аудио (*.wav)...\")\n",
    "        self.convert_thread = convertVideoToAudioThread(self.mp4_file_name, self.audio_file)\n",
    "        self.convert_thread.finished.connect(self.finished_converting)\n",
    "        self.convert_thread.start()\n",
    "        \n",
    "    def get_audio_duration(self, audio_file):\n",
    "        \"\"\"Determine the length of the audio file.\"\"\"\n",
    "        with contextlib.closing(wave.open(audio_file,'r')) as f:\n",
    "            frames = f.getnframes()\n",
    "            rate = f.getframerate()\n",
    "            duration = frames / float(rate)\n",
    "            return duration\n",
    "        \n",
    "    def transcribe_audio(self, audio_file):\n",
    "        \"\"\"Transcribe the audio file.\"\"\"\n",
    "        total_duration = self.get_audio_duration(audio_file) / 10\n",
    "        total_duration = math.ceil(total_duration)\n",
    "        self.td = total_duration\n",
    "        if len(self.output_file_name.toPlainText()) > 0:\n",
    "            self.output_file = self.output_file_name.toPlainText()\n",
    "        else:\n",
    "            self.output_file = \"my_speech_file.txt\"\n",
    "        # Use thread to process in the background and avoid freezing the GUI\n",
    "        self.thread = transcriptionThread(total_duration, audio_file, self.output_file)\n",
    "        self.thread.finished.connect(self.finished_transcribing)\n",
    "        self.thread.change_value.connect(self.set_progress_value)\n",
    "        self.thread.start()\n",
    "        \n",
    "    def finished_converting(self):\n",
    "        \"\"\"Reset message text when conversion is finished.\"\"\"\n",
    "        self.message_label.setText(\"Делаем что-то...\")\n",
    "        self.transcribe_audio(self.audio_file)\n",
    "        \n",
    "    def finished_transcribing(self):\n",
    "        \"\"\"This run when transcription finished to tidy up UI.\"\"\"\n",
    "        self.progress_bar.setValue(100)\n",
    "        self.transcribe_button.setEnabled(True)\n",
    "        self.message_label.setText(\"\")\n",
    "        self.update_text_output()\n",
    "        \n",
    "    def set_progress_value(self, val):\n",
    "        \"\"\"Update progress bar value.\"\"\"\n",
    "        increment = int(math.floor(100*(float(val)/self.td)))\n",
    "        self.progress_bar.setValue(increment)\n",
    "        \n",
    "    def process_and_transcribe_audio(self):\n",
    "        \"\"\"Process the audio into a textual transcription.\"\"\"\n",
    "        self.transcribe_button.setEnabled(False)\n",
    "        self.message_label.setText(\"Converting mp4 to audio (*.wav)...\")\n",
    "        self.convert_mp4_to_wav()\n",
    "        \n",
    "    def update_text_output(self):\n",
    "        \"\"\"Update the text box with the transcribed file.\"\"\"\n",
    "        f = open(self.output_file, \"r\")\n",
    "        self.transcribed_text.setText(f.read())\n",
    "        f.close()\n",
    "        \n",
    "    def new_project(self):\n",
    "        \"\"\"Clear existing fields of data.\"\"\"\n",
    "        self.message_label.setText(\"\")\n",
    "        self.transcribed_text.setText(\"\")\n",
    "        self.selected_video_label.setText(\"\")\n",
    "        self.output_file_name.document().setPlainText(\"\")\n",
    "        self.progress_bar.setValue(0)\n",
    "        \n",
    "    def show_about(self):\n",
    "        \"\"\"Show about message box.\"\"\"\n",
    "        msg = QMessageBox()\n",
    "        msg.setWindowTitle(\"Сидим\")\n",
    "        msg.setText(\"Делаем хакатоны\")\n",
    "        msg.setIcon(QMessageBox.Information)\n",
    "        msg.exec_()\n",
    "        \n",
    "class convertVideoToAudioThread(QThread):\n",
    "    \"\"\"Thread to convert mp4 video file to wav file.\"\"\"\n",
    "    def __init__(self, mp4_file_name, audio_file):\n",
    "        \"\"\"Initialization function.\"\"\"\n",
    "        QThread.__init__(self)\n",
    "        self.mp4_file_name = mp4_file_name\n",
    "        self.audio_file = audio_file\n",
    "    def __del__(self):\n",
    "        \"\"\"Destructor.\"\"\"\n",
    "        self.wait()\n",
    "    def run(self):\n",
    "        \"\"\"Run video conversion task.\"\"\"\n",
    "        audio_clip = AudioFileClip(self.mp4_file_name)\n",
    "        audio_clip.write_audiofile(self.audio_file)\n",
    "        \n",
    "class transcriptionThread(QThread):\n",
    "    \"\"\"Thread to transcribe file from audio to text.\"\"\"\n",
    "    change_value = pyqtSignal(int)\n",
    "    def __init__(self, total_duration, audio_file, output_file):\n",
    "        \"\"\"Initialization function.\"\"\"\n",
    "        QThread.__init__(self)\n",
    "        self.total_duration = total_duration\n",
    "        self.audio_file = audio_file\n",
    "        self.output_file = output_file\n",
    "    def __del__(self):\n",
    "        \"\"\"Destructor.\"\"\"\n",
    "        self.wait()\n",
    "    def run(self):\n",
    "        \"\"\"Run transcription, audio to text.\"\"\"\n",
    "        r = sr.Recognizer()\n",
    "        sound = AudioSegment.from_wav(self.audio_file)\n",
    "        chunks = split_on_silence(sound, min_silence_len = 1000, silence_thresh = sound.dBFS-17)\n",
    "        folder_name = \"audio-chunks\"\n",
    "        if not os.path.isdir(folder_name):\n",
    "            os.mkdir(folder_name)\n",
    "        whole_text = \"\"\n",
    "        \n",
    "        for i, audio_chunk in enumerate(chunks, start=1):\n",
    "            chunk_silent = AudioSegment.silent(duration = 10)\n",
    "            audio_chunk = chunk_silent + audio_chunk + chunk_silent\n",
    "            chunk_filename = os.path.join(folder_name, f\"chunk{i}.wav\")\n",
    "            audio_chunk.export(chunk_filename, format=\"wav\")\n",
    "            \n",
    "            with sr.AudioFile(chunk_filename) as source:\n",
    "                r.adjust_for_ambient_noise(source, duration=0.2)\n",
    "                audio = r.record(source)\n",
    "                try:\n",
    "                    f = open(self.output_file, \"a\")\n",
    "                    f.write(r.recognize_google(audio, language = \"ru-RU\"))\n",
    "                    f.write(\" \")\n",
    "                    text = r.recognize_google(audio, language='ru-RU')\n",
    "                    #allalt = r.recognize_google(audio_listened, language=\"ru-RU\", show_all=True)\n",
    "                    #print(allalt)\n",
    "                except sr.UnknownValueError as e:\n",
    "                    print(\"Error:\", str(e))\n",
    "                else:\n",
    "                    text = f\"{text.capitalize()}. \"\n",
    "                    #print(chunk_filename, \":\", text)\n",
    "                    whole_text += text\n",
    "            print(whole_text)\n",
    "        f.close()\n",
    "        \n",
    "        #for i in range(0, self.total_duration):\n",
    "         #   try:\n",
    "          #      with sr.AudioFile(self.audio_file) as source:\n",
    "           #         audio = r.record(source, offset=i*10, duration=10)\n",
    "            #        f = open(self.output_file, \"a\")\n",
    "             #       f.write(r.recognize_google(audio, language = \"ru-RU\"))\n",
    "              #      f.write(\" \")\n",
    "               # self.change_value.emit(i)\n",
    "            #except:\n",
    "             #   print(\"Найдено неизвестное слово...\")\n",
    "              #  continue\n",
    "            #f.close()\n",
    "            \n",
    "if __name__ == \"__main__\":\n",
    "    import sys\n",
    "    app = QtWidgets.QApplication(sys.argv)\n",
    "    MainWindow = QtWidgets.QMainWindow()\n",
    "    ui = Ui_MainWindow()\n",
    "    ui.setupUi(MainWindow)\n",
    "    MainWindow.show()\n",
    "    sys.exit(app.exec_())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c773d38f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
